[config]
ai_provider = "google"
model = "gemini/gemini-1.5-pro"
max_model_tokens = 100000

[pr_reviewer]
max_files_to_analyze = 30
num_code_suggestions = 3
inline_code_comments = true

[pr_description]
publish_labels = true
generate_ai_title = true

[github_action_config]
auto_review = true
auto_describe = true
auto_improve = false   # disable auto improve for large PRs
